name: meal_logging
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_ml_model_downloader: ^0.4.0+3
  tflite_flutter: ^0.12.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  http: ^1.2.0
  url_launcher: ^6.1.10
  intl: ^0.20.2
  timezone: ^0.10.1
  android_alarm_manager_plus: ^5.0.0
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  firebase_vertexai: ^2.2.0
  flutter_ai_toolkit: ^1.0.0
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome_img.png
    - assets/meal_recommender-2.tflite
    - assets/meal_recommender.onnx
